environment: development
debug: true
host: 0.0.0.0
port: 5000

cors:
  origins:
    - "*"
  allow_credentials: true

storage:
  datasets_root: "./data/datasets"
  results_root: "./data/results"
  temp_root: "./data/tmp"

experiment:
  default_num_runs: 1
  default_parallel_jobs: 4
  default_max_features: 5000
  default_ransac_threshold: 1.0
  default_ransac_confidence: 0.999
  default_ransac_max_iters: 2000
  default_ratio_threshold: 0.75
  post_filter:
    enabled: true
    gms:
      with_rotation: false
      with_scale: false
      threshold_factor: 6
    symmetric_mad:
      mad_k: 3.0

  # 将可视化预处理纳入实验流程
  strict_precompute: true

  # 算法支持现在通过动态发现机制确定，不再硬编码
  # supported_feature_types: 由动态配置管理器自动发现
  # supported_ransac_types: 由动态配置管理器自动发现

  # 图表配置参数
  chart_config:
    pr_curve:
      max_frames: 1000
      max_samples: 3000
      cache_ttl: 300
      allow_on_demand_compute: false
    trajectory:
      max_frames: 500
      cache_ttl: 300
      allow_on_demand_compute: false
    metrics:
      cache_ttl: 300


  # 默认算法参数（集中管理，可被环境覆盖）
  algorithms_defaults:
    features:
      SIFT:
        matcher:
          matcher_type: flann
          ratio_threshold: 0.75
          algorithm: kdtree
          index_params: { algorithm: 1, trees: 5 }
          search_params: { checks: 50 }
      ORB:
        matcher:
          matcher_type: bf
          normType: NORM_HAMMING
          crossCheck: true
          ratio_threshold: 0.75
      AKAZE:
        matcher:
          matcher_type: flann
          algorithm: lsh
          index_params: { algorithm: 6, table_number: 6, key_size: 12, multi_probe_level: 1 }
          search_params: { checks: 50 }
          ratio_threshold: 0.75
      BRISK:
        matcher:
          matcher_type: bf
          normType: NORM_HAMMING
          crossCheck: true
          ratio_threshold: 0.75
      KAZE:
        matcher:
          matcher_type: flann
          algorithm: kdtree
          index_params: { algorithm: 1, trees: 5 }
          search_params: { checks: 50 }
          ratio_threshold: 0.75
      SURF:
        matcher:
          matcher_type: flann
          algorithm: kdtree
          index_params: { algorithm: 1, trees: 5 }
          search_params: { checks: 50 }
          ratio_threshold: 0.75
    ransac:
      STANDARD: { threshold: 1.0, confidence: 0.999, max_iters: 2000, method: RANSAC }
      PROSAC: { threshold: 1.0, confidence: 0.999, max_iters: 2000, method: USAC_PROSAC }

logging:
  level: INFO
  to_stdout: true
# Default configuration
