cors:
  origins:
  - http://localhost:3000
  - http://127.0.0.1:3000
  - http://localhost:5173
database:
  url: sqlite:///vo_benchmark_dev.db
logging:
  level: DEBUG
  requests: true
redis:
  url: redis://localhost:6379/0
server:
  debug: true
  host: 0.0.0.0
  port: 5000
storage:
  # 使用相对路径，ConfigManager 会在运行时规范化为项目根下的绝对路径
  results_root: ./results

