environment: production
debug: false
host: 0.0.0.0
port: 5000

# 生产环境建议通过环境变量覆盖 CORS_ORIGINS，例如：
#   CORS_ORIGINS=http://localhost:3000,https://your.domain
cors:
  origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  allow_credentials: true

logging:
  level: INFO
  to_stdout: true
